### ISSUE TITLE
Building without StartBurp.java

### ISSUE THREAD

**Issue by mrunc** [x-Ai/BurpUnlimitedre#1]
How can we build this without StartBurp.java?

**Comment by mrunc** [comment]
I decompiled the class but it's messy with many "Illegal characters"

**Comment by x-Ai** [comment]
Hi，BurpUnlimitedre build don't need "StartBurp.java"

**Comment by mrunc** [comment]
Maybe that's not a problem but can you help with another thing 
I'm trying to make an app bundle like I used to do with
https://github.com/liftsecurity/BurpSuite-MacOS
but I can't make it work from the app bundle
I can cd into /Applications/Burp Suite Professional.app/Contents/Java and run it successfully with 

    java -javaagent:BurpUnlimitedre.jar -agentpath:lib/libfaketime64.jnilib -jar BurpUnlimitedre.jar
but when i open it from the app it's not giving anything not even an error and when I double click 
BurpUnlimitedre.jar inside " /Applications/Burp Suite Professional.app/Contents/Java" it only opens the spash then closes if I move "Java" folder anywhere outside of the app bundle it works with double clicking

here is the folder structure

/Applications/Burp Suite Professional.app/Contents/Java
--BurpUnlimitedre.jar
--lib/libfaketime64.jnilib
--lib/burpsuite_pro_v1.7.27.jar

here is my build.xml

     <?xml version="1.0" encoding="UTF-8"?>

     <project name="BurpSuite" default="default" basedir=".">
     <property environment="env"/>
     <target name="bundle">
     <taskdef name="bundleapp"
	 classpath="lib/appbundler-1.0ea.jar"
	 classname="com.oracle.appbundler.AppBundlerTask"/>

	<bundleapp
			outputdirectory="."
			name="Burp Suite Professional"
			displayname="Burp Suite Professional"
			identifier="com.portswigger.burp"
			shortversion="1.7.27"
			version="1.7.27"
			icon="resources/icon.icns"
			mainclassname="BurpUnlimited"
			copyright="2017 PortSwigger">

		
		
		<classpath file="BurpUnlimitedre.jar"/>
		<option value="-javaagent:BurpUnlimitedre.jar -agentpath:lib/libfaketime64.jnilib"/>
		<option value="-Xdock:icon=Contents/Resources/${bundle.icon}"/>
		<option value="-Djava.library.path=$APP_ROOT/Contents/Java/"/>
		<option value="-splash:$APP_ROOT/Contents/Resources/splash.png"/>
		<option value="-Dapple.laf.useScreenMenuBar=true"/>
		<option value="-Dcom.apple.macos.use-file-dialog-packages=true"/>
		<option value="-Dcom.apple.macos.useScreenMenuBar=true"/>
		<option value="-Dcom.apple.mrj.application.apple.menu.about.name=${bundle.name}"/>
		<option value="-Dcom.apple.smallTabs=true"/>
		<option value="-Dcom.apple.textantialiasing=true"/>
		<option value="-Dcom.apple.antialiasing=true"/>
		<option value="-Dcom.apple.showGrowBox=false"/>
		
		
		<option value="-Dfile.encoding=UTF-8"/>
		<option value="-Dfile.encoding.pkg=sun.io"/>
		<option value="-Dfile.separator=/"/>
		<arch name="x86_64"/>
		<arch name="i386"/>
	</bundleapp>

	<copy
		todir="./Burp Suite Professional.app/Contents/Resources" filtering="no">
		<fileset dir="resources"/>
	</copy>
	<copy
		todir="./Burp Suite Professional.app/Contents/Java" filtering="no">
		<fileset dir="Java"/>
	</copy>
	<copy
    todir="/Applications/Burp Suite Professional.app" filtering="no">
    <fileset dir="./Burp Suite Professional.app"/>
</copy>
<chmod perm="0755" file="/Applications/Burp Suite Professional.app/Contents/Java/BurpUnlimitedre.jar" />
<chmod perm="0755" file="/Applications/Burp Suite Professional.app/Contents/Java/lib/libfaketime64.jnilib" />
<chmod perm="0755" file="/Applications/Burp Suite Professional.app/Contents/Java/lib/burpsuite_pro_v1.7.27.jar" />
</target>
</project>

**Comment by x-Ai** [comment]
@mrunc please do not use spaces in the path

**Comment by mrunc** [comment]
Still not working as a bundle but now It can be run with double clicking "BurpUnlimitedre.jar" inside "/Applications/BurpSuiteProfessional.app/Contents/Java/"




    <?xml version="1.0" encoding="UTF-8"?>

    <project name="BurpSuite" default="default" basedir=".">
    <property environment="env"/>
    <target name="bundle">
    <taskdef name="bundleapp"
	classpath="lib/appbundler-1.0ea.jar"
	classname="com.oracle.appbundler.AppBundlerTask"/>

	<bundleapp
			outputdirectory="."
			name="BurpSuiteProfessional"
			displayname="Burp Suite Professional"
			identifier="com.portswigger.burp"
			shortversion="1.7.27"
			version="1.7.27"
			icon="resources/icon.icns"
			mainclassname="BurpUnlimited"
			copyright="2017 PortSwigger">

		
		
		<classpath file="BurpUnlimitedre.jar"/>
		<option value="-javaagent:BurpUnlimitedre.jar -agentpath:lib/libfaketime64.jnilib"/>
		<option value="-Xdock:icon=Contents/Resources/${bundle.icon}"/>
		<option value="-Djava.library.path=$APP_ROOT/Contents/Java/"/>
		<option value="-splash:$APP_ROOT/Contents/Resources/splash.png"/>
		<option value="-Dapple.laf.useScreenMenuBar=true"/>
		<option value="-Dcom.apple.macos.use-file-dialog-packages=true"/>
		<option value="-Dcom.apple.macos.useScreenMenuBar=true"/>
		<option value="-Dcom.apple.mrj.application.apple.menu.about.name=${bundle.name}"/>
		<option value="-Dcom.apple.smallTabs=true"/>
		<option value="-Dcom.apple.textantialiasing=true"/>
		<option value="-Dcom.apple.antialiasing=true"/>
		<option value="-Dcom.apple.showGrowBox=false"/>
		
		
		<option value="-Dfile.encoding=UTF-8"/>
		<option value="-Dfile.encoding.pkg=sun.io"/>
		<option value="-Dfile.separator=/"/>
		<arch name="x86_64"/>
		<arch name="i386"/>
	</bundleapp>

	<copy
		todir="./BurpSuiteProfessional.app/Contents/Resources" filtering="no">
		<fileset dir="resources"/>
	</copy>
	<copy
		todir="./BurpSuiteProfessional.app/Contents/Java" filtering="no">
		<fileset dir="Java"/>
	</copy>
	<copy
    todir="/Applications/BurpSuiteProfessional.app" filtering="no">
    <fileset dir="./BurpSuiteProfessional.app"/>
    </copy>
    <chmod perm="0755" file="/Applications/BurpSuiteProfessional.app/Contents/Java/BurpUnlimitedre.jar" />
    <chmod perm="0755" file="/Applications/BurpSuiteProfessional.app/Contents/Java/lib/libfaketime64.jnilib" />
    <chmod perm="0755" file="/Applications/BurpSuiteProfessional.app/Contents/Java/lib/burpsuite_pro_v1.7.27.jar" />
    <chmod perm="0755" file="/Applications/BurpSuiteProfessional.app/Contents/MacOS/JavaAppLauncher" />
    </target>
    </project>
