### ISSUE TITLE
Not work on i386 systems

### ISSUE THREAD

**Issue by huyndnse63331** [x-Ai/BurpUnlimitedre#4]
I have tried many os (both i386 & amd64), only amd64 worked

$: java -javaagent:BurpUnlimitedre.jar -agentpath:lib/libfaketime32.so -jar BurpUnlimitedre.jar

Could not find agent library lib/libfaketime32.so in absolute path, with error: lib/libfaketime32.so: wrong ELF class: ELFCLASS64 (Possible cause: architecture word width mismatch)

Those libs are ELF64, not ELF32, please take a look

**Comment by n4p5ter** [comment]
Where BurpUnlimitedre.jar is located ? Or we should make it ?

**Comment by huyndnse63331** [comment]
its located in the main dir dude, no need to make it

**Comment by n4p5ter** [comment]
if i git clone, there are only 
```
README.md	libs		others		src
```
files
:(

**Comment by huyndnse63331** [comment]
ok i fixed myself for i386 systems ;) worked like a charm
